import { CuratedTrack } from "@/types";

/**
 * Base de morceaux curés pour ChatouneMusic.
 *
 * Chaque morceau est tagué avec 1 à 3 humeurs.
 * Les morceaux multi-humeurs servent de "ponts" entre 2 humeurs
 * et sont privilégiés par l'algorithme de fusion.
 *
 * Pour ajouter un morceau :
 * 1. Trouve-le sur Spotify
 * 2. Copie le lien de partage → extrait l'ID
 * 3. Tague-le avec les humeurs correspondantes
 *
 * TODO: Vérifier manuellement chaque lien Spotify (ouvrir l'URL et confirmer
 * que le titre + artiste correspondent). Les IDs et formats d'URL sont validés
 * par les tests automatisés, mais la correspondance contenu/ID nécessite une
 * vérification humaine ou un appel à l'API Spotify.
 */
export const TRACK_DATABASE: CuratedTrack[] = [
  // ══════════════════════════════════════════
  // 😊 JOYEUX — Pop feel-good, upbeat, soleil
  // ══════════════════════════════════════════
  {
    id: "60nZcImufyMA1MKQY3dcCH",
    title: "Happy",
    artist: "Pharrell Williams",
    album: "G I R L",
    duration: "3:53",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH",
    moods: ["joyeux"],
    energy: 75,
  },
  {
    id: "0VjIjW4GlUZAMYd2vXMi3b",
    title: "Blinding Lights",
    artist: "The Weeknd",
    album: "After Hours",
    duration: "3:20",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi3b",
    moods: ["joyeux", "energique"],
    energy: 80,
  },
  {
    id: "39LLxExYz6ewLAo9BPXL40",
    title: "Levitating",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/39LLxExYz6ewLAo9BPXL40",
    moods: ["joyeux", "fetard"],
    energy: 82,
  },
  {
    id: "7qiZfU4dY1lWllzX7mPBI3",
    title: "Shape of You",
    artist: "Ed Sheeran",
    album: "÷",
    duration: "3:53",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7qiZfU4dY1lWllzX7mPBI3",
    moods: ["joyeux"],
    energy: 70,
  },
  {
    id: "6fi4s2JKEcTXBnTGa2mGPp",
    title: "Walking on Sunshine",
    artist: "Katrina and The Waves",
    album: "Walking on Sunshine",
    duration: "3:58",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6fi4s2JKEcTXBnTGa2mGPp",
    moods: ["joyeux"],
    energy: 80,
  },
  {
    id: "1DIXPcTDzTj8ZMHt3PDt8p",
    title: "Can't Stop the Feeling!",
    artist: "Justin Timberlake",
    album: "Trolls (Original Motion Picture Soundtrack)",
    duration: "3:56",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1DIXPcTDzTj8ZMHt3PDt8p",
    moods: ["joyeux", "fetard"],
    energy: 78,
  },
  {
    id: "3BovdzfaX4jb5KFQwoPfAw",
    title: "Good as Hell",
    artist: "Lizzo",
    album: "Cuz I Love You (Super Deluxe)",
    duration: "2:39",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3BovdzfaX4jb5KFQwoPfAw",
    moods: ["joyeux", "energique"],
    energy: 78,
  },
  {
    id: "2H1047e0oMSj10dgp7p2VG",
    title: "I Gotta Feeling",
    artist: "Black Eyed Peas",
    album: "THE E.N.D.",
    duration: "4:49",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2H1047e0oMSj10dgp7p2VG",
    moods: ["joyeux", "fetard"],
    energy: 85,
  },
  {
    id: "6dGnYIeXmHdcikdzNNDMm2",
    title: "Here Comes the Sun",
    artist: "The Beatles",
    album: "Abbey Road",
    duration: "3:06",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6dGnYIeXmHdcikdzNNDMm2",
    moods: ["joyeux", "chill"],
    energy: 45,
  },
  {
    id: "2RlgNHKcydI9sayD2Df2xp",
    title: "Mr. Blue Sky",
    artist: "Electric Light Orchestra",
    album: "Out of the Blue",
    duration: "5:03",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2RlgNHKcydI9sayD2Df2xp",
    moods: ["joyeux"],
    energy: 75,
  },
  {
    id: "1dNIEtp7AY3oDAKCGg2XkH",
    title: "On Top of the World",
    artist: "Imagine Dragons",
    album: "Night Visions",
    duration: "3:12",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1dNIEtp7AY3oDAKCGg2XkH",
    moods: ["joyeux"],
    energy: 72,
  },
  {
    id: "1YLJIRv1F2YZvl5MZ7Jpke",
    title: "Lovely Day",
    artist: "Bill Withers",
    album: "Menagerie",
    duration: "4:14",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1YLJIRv1F2YZvl5MZ7Jpke",
    moods: ["joyeux", "chill"],
    energy: 50,
  },
  {
    id: "1EzrEOXmMH3G43AXT1y7pA",
    title: "I'm Yours",
    artist: "Jason Mraz",
    album: "We Sing. We Dance. We Steal Things.",
    duration: "4:03",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1EzrEOXmMH3G43AXT1y7pA",
    moods: ["joyeux", "romantique"],
    energy: 45,
  },
  {
    id: "2goLsvvODILDzeeiT4dAoR",
    title: "Papaoutai",
    artist: "Stromae",
    album: "Racine carrée",
    duration: "3:53",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2goLsvvODILDzeeiT4dAoR",
    moods: ["joyeux", "energique"],
    energy: 72,
  },
  {
    id: "3YJJjQPAbDT7mGpX3WtQ9A",
    title: "Je veux",
    artist: "Zaz",
    album: "Zaz",
    duration: "3:35",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3YJJjQPAbDT7mGpX3WtQ9A",
    moods: ["joyeux"],
    energy: 70,
  },
  {
    id: "0RiRZpuVRbi7oqRdSMwhQY",
    title: "Tout oublier",
    artist: "Angèle ft. Roméo Elvis",
    album: "Brol",
    duration: "3:09",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0RiRZpuVRbi7oqRdSMwhQY",
    moods: ["joyeux", "chill"],
    energy: 65,
  },
  {
    id: "24Yi9hE78yPEhZ22DKOCvr",
    title: "Shut Up and Dance",
    artist: "WALK THE MOON",
    album: "TALKING IS HARD",
    duration: "3:19",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/24Yi9hE78yPEhZ22DKOCvr",
    moods: ["joyeux", "fetard"],
    energy: 80,
  },
  {
    id: "32OlwWuMpZ6b0aN2RZOeMS",
    title: "Uptown Funk",
    artist: "Mark Ronson ft. Bruno Mars",
    album: "Uptown Special",
    duration: "4:30",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS",
    moods: ["joyeux", "energique", "fetard"],
    energy: 90,
  },
  {
    id: "2nLtzopw4rPReszdYBJU6h",
    title: "Dynamite",
    artist: "BTS",
    album: "Dynamite",
    duration: "3:19",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h",
    moods: ["joyeux"],
    energy: 76,
  },
  {
    id: "6habFhsOp2NvshLv26DqMb",
    title: "Joyeux anniversaire",
    artist: "Stromae",
    album: "Multitude",
    duration: "2:58",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6habFhsOp2NvshLv26DqMb",
    moods: ["joyeux", "melancolique"],
    energy: 55,
  },

  // ══════════════════════════════════════════
  // 💕 ROMANTIQUE — Love songs, ballades, tendresse
  // ══════════════════════════════════════════
  {
    id: "3d9DChrdc6BOeFsbrZ3Is0",
    title: "All of Me",
    artist: "John Legend",
    album: "Love in the Future",
    duration: "4:29",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3d9DChrdc6BOeFsbrZ3Is0",
    moods: ["romantique"],
    energy: 35,
  },
  {
    id: "1Me1lY0dJnEtEbMYJVpqBe",
    title: "Perfect",
    artist: "Ed Sheeran",
    album: "÷",
    duration: "4:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1Me1lY0dJnEtEbMYJVpqBe",
    moods: ["romantique", "chill"],
    energy: 30,
  },
  {
    id: "0u2P5u6lvoDfwTYjAADbn4",
    title: "Lover",
    artist: "Taylor Swift",
    album: "Lover",
    duration: "3:41",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0u2P5u6lvoDfwTYjAADbn4",
    moods: ["romantique", "joyeux"],
    energy: 45,
  },
  {
    id: "3Ti0GdlrotgmFbVzYsEMjF",
    title: "Thinking Out Loud",
    artist: "Ed Sheeran",
    album: "×",
    duration: "4:41",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3Ti0GdlrotgmFbVzYsEMjF",
    moods: ["romantique", "chill"],
    energy: 35,
  },
  {
    id: "2xLMifQCjDGFmkHkpNLD9h",
    title: "Just the Way You Are",
    artist: "Bruno Mars",
    album: "Doo-Wops & Hooligans",
    duration: "3:40",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2xLMifQCjDGFmkHkpNLD9h",
    moods: ["romantique"],
    energy: 55,
  },
  {
    id: "4gphxUgq0JSFv2BCLhNDiO",
    title: "A Thousand Years",
    artist: "Christina Perri",
    album: "The Twilight Saga: Breaking Dawn",
    duration: "4:45",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4gphxUgq0JSFv2BCLhNDiO",
    moods: ["romantique"],
    energy: 30,
  },
  {
    id: "0pqnGHJpmpxLKifKRmU6WP",
    title: "Crazy in Love",
    artist: "Beyoncé ft. JAY-Z",
    album: "Dangerously in Love",
    duration: "3:56",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0pqnGHJpmpxLKifKRmU6WP",
    moods: ["romantique", "energique", "fetard"],
    energy: 75,
  },
  {
    id: "27u7t9kzBjTGFNMbqjYQOo",
    title: "L'amour est un oiseau rebelle (Habanera)",
    artist: "Maria Callas",
    album: "Carmen",
    duration: "4:54",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/27u7t9kzBjTGFNMbqjYQOo",
    moods: ["romantique", "melancolique"],
    energy: 40,
  },
  {
    id: "2TpxZ7JUBn3uw46aR7qd6V",
    title: "All You Need Is Love",
    artist: "The Beatles",
    album: "Magical Mystery Tour",
    duration: "3:48",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2TpxZ7JUBn3uw46aR7qd6V",
    moods: ["romantique", "joyeux"],
    energy: 50,
  },
  {
    id: "3AJwUDP919kvQ9QcozQPxg",
    title: "Yellow",
    artist: "Coldplay",
    album: "Parachutes",
    duration: "4:29",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3AJwUDP919kvQ9QcozQPxg",
    moods: ["romantique", "melancolique"],
    energy: 40,
  },
  {
    id: "1BxfuPKGuaTgP7aM0Bbdwr",
    title: "Endless Love",
    artist: "Lionel Richie, Diana Ross",
    album: "Endless Love",
    duration: "4:27",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1BxfuPKGuaTgP7aM0Bbdwr",
    moods: ["romantique"],
    energy: 30,
  },
  {
    id: "40riOy7x9W7GXjyGp4pjAv",
    title: "Love On Top",
    artist: "Beyoncé",
    album: "4",
    duration: "4:27",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/40riOy7x9W7GXjyGp4pjAv",
    moods: ["romantique", "joyeux"],
    energy: 70,
  },
  {
    id: "7ovUcF5uHTBRzUpB6ZOmvt",
    title: "Die With A Smile",
    artist: "Lady Gaga, Bruno Mars",
    album: "Die With A Smile",
    duration: "4:05",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7ovUcF5uHTBRzUpB6ZOmvt",
    moods: ["romantique"],
    energy: 40,
  },
  {
    id: "3CeCwYWvdfXbZLKhxaYOjt",
    title: "Unchained Melody",
    artist: "The Righteous Brothers",
    album: "Just Once in My Life",
    duration: "3:36",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3CeCwYWvdfXbZLKhxaYOjt",
    moods: ["romantique"],
    energy: 30,
  },
  {
    id: "2dHCNMXXnC8mRiaWEfnaON",
    title: "Que je t'aime",
    artist: "Johnny Hallyday",
    album: "Johnny Hallyday",
    duration: "3:37",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2dHCNMXXnC8mRiaWEfnaON",
    moods: ["romantique", "energique"],
    energy: 65,
  },
  {
    id: "7BKLCZ1jbUBVqRi2FVlTVw",
    title: "Amoureuse",
    artist: "Véronique Sanson",
    album: "Amoureuse",
    duration: "3:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7BKLCZ1jbUBVqRi2FVlTVw",
    moods: ["romantique", "chill"],
    energy: 35,
  },
  {
    id: "6UelLqGlWMcVH1E5c4H7lY",
    title: "Watermelon Sugar",
    artist: "Harry Styles",
    album: "Fine Line",
    duration: "2:54",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6UelLqGlWMcVH1E5c4H7lY",
    moods: ["romantique", "joyeux"],
    energy: 60,
  },
  {
    id: "6ADSaE87h4nP2ECsnqntIO",
    title: "La nuit je mens",
    artist: "Alain Bashung",
    album: "Fantaisie militaire",
    duration: "5:40",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6ADSaE87h4nP2ECsnqntIO",
    moods: ["romantique", "melancolique"],
    energy: 30,
  },

  // ══════════════════════════════════════════
  // 😌 CHILL — Lo-fi, ambient, relax, acoustic
  // ══════════════════════════════════════════
  {
    id: "5HCyWlXZPP0y6Gqq8TgA20",
    title: "Sunflower",
    artist: "Post Malone, Swae Lee",
    album: "Spider-Man: Into the Spider-Verse",
    duration: "2:38",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/5HCyWlXZPP0y6Gqq8TgA20",
    moods: ["chill"],
    energy: 50,
  },
  {
    id: "0VjIjW4GlUZAMYd2vXMi4b",
    title: "Blinding Lights (Remix)",
    artist: "The Weeknd",
    album: "After Hours (Deluxe)",
    duration: "3:22",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0VjIjW4GlUZAMYd2vXMi4b",
    moods: ["chill"],
    energy: 55,
  },
  {
    id: "7yyRTcZmCiyzzJlNzGC9Ol",
    title: "Falling",
    artist: "Harry Styles",
    album: "Fine Line",
    duration: "4:00",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7yyRTcZmCiyzzJlNzGC9Ol",
    moods: ["chill", "melancolique"],
    energy: 25,
  },
  {
    id: "3KkXRkHbMCARz0aVfEt68P",
    title: "Sunflower, Vol. 6",
    artist: "Harry Styles",
    album: "Fine Line",
    duration: "3:42",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3KkXRkHbMCARz0aVfEt68P",
    moods: ["chill", "joyeux"],
    energy: 45,
  },
  {
    id: "6PQ88X9TkUIAUIZJHW2upE",
    title: "Clocks",
    artist: "Coldplay",
    album: "A Rush of Blood to the Head",
    duration: "5:07",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6PQ88X9TkUIAUIZJHW2upE",
    moods: ["chill"],
    energy: 55,
  },
  {
    id: "3hRV0jL3vUpRrcy398teAU",
    title: "Electric Feel",
    artist: "MGMT",
    album: "Oracular Spectacular",
    duration: "3:49",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3hRV0jL3vUpRrcy398teAU",
    moods: ["chill", "fetard"],
    energy: 60,
  },
  {
    id: "0tgVpDi06FyKpA1z0VMD4v",
    title: "Perfect Places",
    artist: "Lorde",
    album: "Melodrama",
    duration: "3:41",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v",
    moods: ["chill", "melancolique"],
    energy: 50,
  },
  {
    id: "1rfofaqEpACxVEHIZBJe6W",
    title: "Hateful",
    artist: "The Clash",
    album: "London Calling",
    duration: "2:44",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1rfofaqEpACxVEHIZBJe6W",
    moods: ["chill"],
    energy: 45,
  },
  {
    id: "4cluDES4hQEUhmXj6TXkSo",
    title: "Alright",
    artist: "Supergrass",
    album: "I Should Coco",
    duration: "3:20",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4cluDES4hQEUhmXj6TXkSo",
    moods: ["chill", "joyeux"],
    energy: 55,
  },
  {
    id: "7GhIk7Il098yCjg4BQjzvb",
    title: "Never Going Back Again",
    artist: "Fleetwood Mac",
    album: "Rumours",
    duration: "2:14",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7GhIk7Il098yCjg4BQjzvb",
    moods: ["chill"],
    energy: 30,
  },
  {
    id: "3a1lNhkSLSkpJE4MSHpDu9",
    title: "Chanson sur ma drôle de vie",
    artist: "Véronique Sanson",
    album: "Amoureuse",
    duration: "4:50",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3a1lNhkSLSkpJE4MSHpDu9",
    moods: ["chill", "melancolique"],
    energy: 30,
  },
  {
    id: "5ChkMS8OtdzJeqyybCc9R5",
    title: "Bitter Sweet Symphony",
    artist: "The Verve",
    album: "Urban Hymns",
    duration: "5:59",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/5ChkMS8OtdzJeqyybCc9R5",
    moods: ["chill", "melancolique"],
    energy: 50,
  },
  {
    id: "7w87IxuO7BDcJ3YUqCyMTT",
    title: "Banana Pancakes",
    artist: "Jack Johnson",
    album: "In Between Dreams",
    duration: "3:12",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7w87IxuO7BDcJ3YUqCyMTT",
    moods: ["chill"],
    energy: 35,
  },
  {
    id: "6SpLc7EXZIPpy0sVko0aoU",
    title: "Sous le vent",
    artist: "Garou, Céline Dion",
    album: "Seul",
    duration: "4:04",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6SpLc7EXZIPpy0sVko0aoU",
    moods: ["chill", "romantique"],
    energy: 45,
  },
  {
    id: "0ct6r3EGTcMLPaxuIJBaOj",
    title: "Something",
    artist: "The Beatles",
    album: "Abbey Road",
    duration: "3:03",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0ct6r3EGTcMLPaxuIJBaOj",
    moods: ["chill", "romantique"],
    energy: 35,
  },
  {
    id: "0lYBSQXN6pIgZLMgFq3tJt",
    title: "Put Your Records On",
    artist: "Corinne Bailey Rae",
    album: "Corinne Bailey Rae",
    duration: "3:35",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0lYBSQXN6pIgZLMgFq3tJt",
    moods: ["chill", "joyeux"],
    energy: 45,
  },
  {
    id: "3n3Ppam7vgaVa1iaRUc9Lp",
    title: "Mr. Brightside",
    artist: "The Killers",
    album: "Hot Fuss",
    duration: "3:42",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3n3Ppam7vgaVa1iaRUc9Lp",
    moods: ["chill", "energique"],
    energy: 65,
  },
  {
    id: "3MODES4TNtygekLl146Dxd",
    title: "Alors on danse",
    artist: "Stromae",
    album: "Cheese",
    duration: "4:33",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3MODES4TNtygekLl146Dxd",
    moods: ["chill", "fetard"],
    energy: 60,
  },
  {
    id: "7oK9VyNzrYvRFo7nQEYkWN",
    title: "Mr. Sandman",
    artist: "The Chordettes",
    album: "The Best Of The Chordettes",
    duration: "2:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7oK9VyNzrYvRFo7nQEYkWN",
    moods: ["chill", "romantique"],
    energy: 40,
  },

  // ══════════════════════════════════════════
  // 🥺 MÉLANCOLIQUE — Émotionnel, introspectif, folk
  // ══════════════════════════════════════════
  {
    id: "4cOdK2LGgbkSLaamaiLfFb",
    title: "Someone Like You",
    artist: "Adele",
    album: "21",
    duration: "4:45",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4cOdK2LGgbkSLaamaiLfFb",
    moods: ["melancolique"],
    energy: 25,
  },
  {
    id: "3JOVTQ5h8HGFnDdp4VT3MP",
    title: "Skinny Love",
    artist: "Bon Iver",
    album: "For Emma, Forever Ago",
    duration: "3:58",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3JOVTQ5h8HGFnDdp4VT3MP",
    moods: ["melancolique", "chill"],
    energy: 20,
  },
  {
    id: "7LVHVU3tWfcxj5aiPFEW4Q",
    title: "Fix You",
    artist: "Coldplay",
    album: "X&Y",
    duration: "4:55",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7LVHVU3tWfcxj5aiPFEW4Q",
    moods: ["melancolique", "romantique"],
    energy: 40,
  },
  {
    id: "3T4tUhGYeRNVUGevb0wThu",
    title: "Creep",
    artist: "Radiohead",
    album: "Pablo Honey",
    duration: "3:56",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3T4tUhGYeRNVUGevb0wThu",
    moods: ["melancolique"],
    energy: 45,
  },
  {
    id: "34gCuhDGsG4bRPIf9bb02f",
    title: "Bohemian Rhapsody",
    artist: "Queen",
    album: "A Night at the Opera",
    duration: "5:55",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/34gCuhDGsG4bRPIf9bb02f",
    moods: ["melancolique", "energique"],
    energy: 55,
  },
  {
    id: "5anSgIcEUJ6b1RaBfN3hqY",
    title: "Ne me quitte pas",
    artist: "Jacques Brel",
    album: "Ne me quitte pas",
    duration: "4:47",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/5anSgIcEUJ6b1RaBfN3hqY",
    moods: ["melancolique", "romantique"],
    energy: 25,
  },
  {
    id: "3YRCqOhFifThpSRFJ1VWFM",
    title: "Space Oddity",
    artist: "David Bowie",
    album: "David Bowie (Space Oddity)",
    duration: "5:18",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3YRCqOhFifThpSRFJ1VWFM",
    moods: ["melancolique"],
    energy: 35,
  },
  {
    id: "22sLuJYcvZOSoLLRYev1s5",
    title: "Mad World",
    artist: "Gary Jules",
    album: "Trading Snakeoil for Wolftickets",
    duration: "3:08",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/22sLuJYcvZOSoLLRYev1s5",
    moods: ["melancolique"],
    energy: 15,
  },
  {
    id: "3gsCAGsWr2pEN4fdGnfCfJ",
    title: "Hallelujah",
    artist: "Jeff Buckley",
    album: "Grace",
    duration: "6:53",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3gsCAGsWr2pEN4fdGnfCfJ",
    moods: ["melancolique", "romantique"],
    energy: 20,
  },
  {
    id: "2VxeLyX666F8uXCJ0dZF8B",
    title: "Shallow",
    artist: "Lady Gaga, Bradley Cooper",
    album: "A Star Is Born",
    duration: "3:35",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2VxeLyX666F8uXCJ0dZF8B",
    moods: ["melancolique", "romantique"],
    energy: 50,
  },
  {
    id: "0GONea6G2XdnhkArcKEEMi",
    title: "Dernière danse",
    artist: "Indila",
    album: "Mini World",
    duration: "3:34",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0GONea6G2XdnhkArcKEEMi",
    moods: ["melancolique", "energique"],
    energy: 60,
  },
  {
    id: "7snQQk1zcKl8gZ92AnueZW",
    title: "When the Party's Over",
    artist: "Billie Eilish",
    album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    duration: "3:16",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7snQQk1zcKl8gZ92AnueZW",
    moods: ["melancolique"],
    energy: 15,
  },
  {
    id: "4fzsfWzRhPawzqhX8Qt9F3",
    title: "Je suis malade",
    artist: "Serge Lama",
    album: "Je suis malade",
    duration: "5:15",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4fzsfWzRhPawzqhX8Qt9F3",
    moods: ["melancolique"],
    energy: 35,
  },
  {
    id: "0nrRP2bk19rLc0NV8KZqWJ",
    title: "Somebody That I Used to Know",
    artist: "Gotye ft. Kimbra",
    album: "Making Mirrors",
    duration: "4:04",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0nrRP2bk19rLc0NV8KZqWJ",
    moods: ["melancolique"],
    energy: 50,
  },
  {
    id: "2TIlqbIneP0ZY1O0EzYLlc",
    title: "Je l'aime à mourir",
    artist: "Francis Cabrel",
    album: "Les Murs de poussière",
    duration: "4:56",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2TIlqbIneP0ZY1O0EzYLlc",
    moods: ["melancolique", "romantique"],
    energy: 30,
  },
  {
    id: "4RvWPyQ5RL0ao9LPZeSouE",
    title: "Everybody Hurts",
    artist: "R.E.M.",
    album: "Automatic for the People",
    duration: "5:17",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4RvWPyQ5RL0ao9LPZeSouE",
    moods: ["melancolique"],
    energy: 20,
  },
  {
    id: "1vrd6UOGamcKNGnSHJQlSt",
    title: "Retrograde",
    artist: "James Blake",
    album: "Overgrown",
    duration: "3:42",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1vrd6UOGamcKNGnSHJQlSt",
    moods: ["melancolique", "chill"],
    energy: 35,
  },
  {
    id: "3xrQ4vDmLhGHGUSaBkGcOQ",
    title: "La Bohème",
    artist: "Charles Aznavour",
    album: "La Bohème",
    duration: "3:38",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3xrQ4vDmLhGHGUSaBkGcOQ",
    moods: ["melancolique"],
    energy: 30,
  },
  {
    id: "2QZ7WLBE1EGiFYxBMbMBRb",
    title: "Let Her Go",
    artist: "Passenger",
    album: "All the Little Lights",
    duration: "4:12",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2QZ7WLBE1EGiFYxBMbMBRb",
    moods: ["melancolique", "chill"],
    energy: 35,
  },

  // ══════════════════════════════════════════
  // ⚡ ÉNERGIQUE — Workout, electronic, power
  // ══════════════════════════════════════════
  {
    id: "62PaSfnXSMyLshYJrlTuL3",
    title: "Stronger",
    artist: "Kanye West",
    album: "Graduation",
    duration: "5:12",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/62PaSfnXSMyLshYJrlTuL3",
    moods: ["energique"],
    energy: 85,
  },
  {
    id: "2KH16WveTQWT6KOG9Rg6e2",
    title: "Eye of the Tiger",
    artist: "Survivor",
    album: "Eye of the Tiger",
    duration: "4:04",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2KH16WveTQWT6KOG9Rg6e2",
    moods: ["energique", "joyeux"],
    energy: 85,
  },
  {
    id: "3PfIrDoz19wz7qK7tYeu62",
    title: "Don't Start Now",
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    duration: "3:03",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3PfIrDoz19wz7qK7tYeu62",
    moods: ["energique", "fetard"],
    energy: 85,
  },
  {
    id: "6Sy9BUbgFse0n0LPA5lwy5",
    title: "Lose Yourself",
    artist: "Eminem",
    album: "8 Mile Soundtrack",
    duration: "5:26",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6Sy9BUbgFse0n0LPA5lwy5",
    moods: ["energique"],
    energy: 90,
  },
  {
    id: "2CEgGE6aESpnmtfiZwYlbV",
    title: "Titanium",
    artist: "David Guetta ft. Sia",
    album: "Nothing but the Beat",
    duration: "4:05",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2CEgGE6aESpnmtfiZwYlbV",
    moods: ["energique", "fetard"],
    energy: 82,
  },
  {
    id: "6ORqU0bHbVCRjXm9AjyHyZ",
    title: "Take On Me",
    artist: "a-ha",
    album: "Hunting High and Low",
    duration: "3:48",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6ORqU0bHbVCRjXm9AjyHyZ",
    moods: ["energique", "joyeux"],
    energy: 78,
  },
  {
    id: "3ZFTkvIE7kyPt6Nu3PEa7V",
    title: "Crazy",
    artist: "Gnarls Barkley",
    album: "St. Elsewhere",
    duration: "2:58",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3ZFTkvIE7kyPt6Nu3PEa7V",
    moods: ["energique"],
    energy: 70,
  },
  {
    id: "2Fxmhks0bxGSBdJ92vM42m",
    title: "bad guy",
    artist: "Billie Eilish",
    album: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    duration: "3:14",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2Fxmhks0bxGSBdJ92vM42m",
    moods: ["energique", "fetard"],
    energy: 75,
  },
  {
    id: "6dBUzqjtbnSfGB1dCjUQuK",
    title: "Feel Good Inc.",
    artist: "Gorillaz",
    album: "Demon Days",
    duration: "3:41",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6dBUzqjtbnSfGB1dCjUQuK",
    moods: ["energique", "chill"],
    energy: 65,
  },
  {
    id: "0e7ipj03S05BNilyu5bRzt",
    title: "Thriller",
    artist: "Michael Jackson",
    album: "Thriller",
    duration: "5:57",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0e7ipj03S05BNilyu5bRzt",
    moods: ["energique"],
    energy: 80,
  },
  {
    id: "7cjlfMyOb6bEBKvGOT1MVq",
    title: "Ça ira",
    artist: "Joyce Jonathan",
    album: "Sur mes gardes",
    duration: "3:18",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7cjlfMyOb6bEBKvGOT1MVq",
    moods: ["energique", "joyeux"],
    energy: 65,
  },
  {
    id: "7ouMYWpwJ422jRcDASZB7P",
    title: "Knights of Cydonia",
    artist: "Muse",
    album: "Black Holes and Revelations",
    duration: "6:06",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7ouMYWpwJ422jRcDASZB7P",
    moods: ["energique"],
    energy: 90,
  },
  {
    id: "4pbJqGIASGPr0ZpGpnWkDn",
    title: "We Will Rock You",
    artist: "Queen",
    album: "News of the World",
    duration: "2:02",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4pbJqGIASGPr0ZpGpnWkDn",
    moods: ["energique"],
    energy: 88,
  },
  {
    id: "20I6sIOMTCkB6w7rDAEEgR",
    title: "Another One Bites the Dust",
    artist: "Queen",
    album: "The Game",
    duration: "3:35",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/20I6sIOMTCkB6w7rDAEEgR",
    moods: ["energique", "fetard"],
    energy: 80,
  },
  {
    id: "7hQJA50XrCWABAu5v6QZ4i",
    title: "Superstition",
    artist: "Stevie Wonder",
    album: "Talking Book",
    duration: "4:26",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7hQJA50XrCWABAu5v6QZ4i",
    moods: ["energique", "joyeux"],
    energy: 75,
  },
  {
    id: "2muYkKzccNMZSYFe2cXkEV",
    title: "La Tribu de Dana",
    artist: "Manau",
    album: "Panique Celtique",
    duration: "4:29",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2muYkKzccNMZSYFe2cXkEV",
    moods: ["energique", "fetard"],
    energy: 82,
  },
  {
    id: "2tpWsVSb9UEmDRxAl1zhX1",
    title: "Believer",
    artist: "Imagine Dragons",
    album: "Evolve",
    duration: "3:24",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2tpWsVSb9UEmDRxAl1zhX1",
    moods: ["energique"],
    energy: 85,
  },

  // ══════════════════════════════════════════
  // 🎉 FÊTARD — Club, dance, EDM, reggaeton
  // ══════════════════════════════════════════
  {
    id: "0deORnapZgrEFMVGxZzdEG",
    title: "One Kiss",
    artist: "Calvin Harris, Dua Lipa",
    album: "One Kiss",
    duration: "3:34",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0deORnapZgrEFMVGxZzdEG",
    moods: ["fetard", "joyeux"],
    energy: 88,
  },
  {
    id: "6Nvjt5MINhRf4MmKjPjLaH",
    title: "Get Lucky",
    artist: "Daft Punk ft. Pharrell Williams",
    album: "Random Access Memories",
    duration: "6:09",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6Nvjt5MINhRf4MmKjPjLaH",
    moods: ["fetard", "chill"],
    energy: 70,
  },
  {
    id: "6KBYefIoo7KydImq1ERMgR",
    title: "Despacito",
    artist: "Luis Fonsi ft. Daddy Yankee",
    album: "Vida",
    duration: "4:42",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6KBYefIoo7KydImq1ERMgR",
    moods: ["fetard", "romantique"],
    energy: 75,
  },
  {
    id: "1zi7xx7UVEFkmKfv06H8x0",
    title: "One More Time",
    artist: "Daft Punk",
    album: "Discovery",
    duration: "5:20",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1zi7xx7UVEFkmKfv06H8x0",
    moods: ["fetard"],
    energy: 85,
  },
  {
    id: "5aAx2yezTd8zXrkmtKl66Z",
    title: "Stayin' Alive",
    artist: "Bee Gees",
    album: "Saturday Night Fever",
    duration: "4:45",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/5aAx2yezTd8zXrkmtKl66Z",
    moods: ["fetard", "joyeux"],
    energy: 75,
  },
  {
    id: "1p80LdxRV74UKvRbTfN86F",
    title: "Séquence émotion",
    artist: "Polo & Pan",
    album: "Caravelle",
    duration: "4:17",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1p80LdxRV74UKvRbTfN86F",
    moods: ["fetard", "chill"],
    energy: 65,
  },
  {
    id: "5a2EaR3hamoenG9rDuVn2yF",
    title: "Party Rock Anthem",
    artist: "LMFAO ft. Lauren Bennett, GoonRock",
    album: "Sorry for Party Rocking",
    duration: "4:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/5a2EaR3hamoenG9rDuVn2yF",
    moods: ["fetard"],
    energy: 90,
  },
  {
    id: "0YVGS57TJ3MfKEKtHSDB7A",
    title: "Dancing Queen",
    artist: "ABBA",
    album: "Arrival",
    duration: "3:51",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0YVGS57TJ3MfKEKtHSDB7A",
    moods: ["fetard", "joyeux"],
    energy: 80,
  },
  {
    id: "4nrPB8O7Y7wsOCJdgXkthe",
    title: "Wake Me Up",
    artist: "Avicii",
    album: "True",
    duration: "4:07",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4nrPB8O7Y7wsOCJdgXkthe",
    moods: ["fetard", "energique"],
    energy: 85,
  },
  {
    id: "2cGxRwrMyEAp8dEbuZaVfU",
    title: "Sweet Dreams",
    artist: "Eurythmics",
    album: "Sweet Dreams (Are Made of This)",
    duration: "3:36",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2cGxRwrMyEAp8dEbuZaVfU",
    moods: ["fetard"],
    energy: 75,
  },
  {
    id: "0CT6HixJ6cv3SYANeHTNgP",
    title: "Turn Down for What",
    artist: "DJ Snake, Lil Jon",
    album: "Turn Down for What",
    duration: "3:33",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0CT6HixJ6cv3SYANeHTNgP",
    moods: ["fetard", "energique"],
    energy: 95,
  },
  {
    id: "7dt6x5M1jzdTEt8oCbisTK",
    title: "Hung Up",
    artist: "Madonna",
    album: "Confessions on a Dance Floor",
    duration: "5:36",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7dt6x5M1jzdTEt8oCbisTK",
    moods: ["fetard"],
    energy: 82,
  },
  {
    id: "7tFiyTwD0nx5a1eklYtX2J",
    title: "Firework",
    artist: "Katy Perry",
    album: "Teenage Dream",
    duration: "3:48",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7tFiyTwD0nx5a1eklYtX2J",
    moods: ["fetard", "joyeux"],
    energy: 80,
  },
  {
    id: "2dpaYNEQHiRxtZbfNsse99",
    title: "Ça plane pour moi",
    artist: "Plastic Bertrand",
    album: "An 1",
    duration: "3:12",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2dpaYNEQHiRxtZbfNsse99",
    moods: ["fetard", "energique"],
    energy: 88,
  },
  {
    id: "4Dvkj6JhhA12EX05fT5y56",
    title: "As It Was",
    artist: "Harry Styles",
    album: "Harry's House",
    duration: "2:47",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4Dvkj6JhhA12EX05fT5y56",
    moods: ["fetard", "joyeux"],
    energy: 70,
  },

  // ══════════════════════════════════════════
  // 🎵 SÉLECTION PERSO — Chatoune & son amour 💕
  // ══════════════════════════════════════════

  // 😊 Joyeux
  {
    id: "6RKuyWarJu8SMrflntmyXx",
    title: "La Vie en rose",
    artist: "Édith Piaf",
    album: "La Vie en rose",
    duration: "3:07",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6RKuyWarJu8SMrflntmyXx",
    moods: ["joyeux", "romantique"],
    energy: 45,
    note: "Pour aimer la vie un peu plus fort",
  },
  {
    id: "46ylgBYgbb5IltjoQrVnFe",
    title: "Le Sud",
    artist: "Nino Ferrer",
    album: "Les 50 Plus Belles Chansons",
    duration: "4:48",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/46ylgBYgbb5IltjoQrVnFe",
    moods: ["joyeux", "chill"],
    energy: 40,
    note: "À écouter pour s'imaginer dans le sud",
  },
  {
    id: "45S5WTQEGOB1VHr1Q4FuPl",
    title: "Golden",
    artist: "Harry Styles",
    album: "Fine Line",
    duration: "3:29",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/45S5WTQEGOB1VHr1Q4FuPl",
    moods: ["joyeux", "chill"],
    energy: 55,
    note: "Pour des bonnes vibes en pensant à Lolo",
  },
  {
    id: "6XixnpCotremjjIMHfZ01D",
    title: "Africa",
    artist: "Toto",
    album: "Toto IV",
    duration: "4:55",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6XixnpCotremjjIMHfZ01D",
    moods: ["joyeux", "energique"],
    energy: 65,
    note: "Pour revivre l'Afrique du Sud",
  },
  {
    id: "7tqhbajSfrz2F7E1Z75ASX",
    title: "Ain't No Mountain High Enough",
    artist: "Marvin Gaye & Tammi Terrell",
    album: "United",
    duration: "2:28",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7tqhbajSfrz2F7E1Z75ASX",
    moods: ["joyeux", "romantique", "energique"],
    energy: 70,
    note: "Pour chanter très fort et assumer",
  },
  {
    id: "0xmjwnQ3FNE6HuWCt2nHdZ",
    title: "Where Is the Love?",
    artist: "Black Eyed Peas",
    album: "Elephunk",
    duration: "4:32",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0xmjwnQ3FNE6HuWCt2nHdZ",
    moods: ["joyeux", "melancolique"],
    energy: 55,
    note: "Pour une vibe MTV 2003",
  },
  {
    id: "3U5JVgI2x4rDyHGObzJfNf",
    title: "Unwritten",
    artist: "Natasha Bedingfield",
    album: "Unwritten",
    duration: "4:18",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3U5JVgI2x4rDyHGObzJfNf",
    moods: ["joyeux", "energique"],
    energy: 75,
    note: "Pour continuer de la chanter à tue-tête",
  },
  {
    id: "2ixsaeFioXJmMgkkbd4uj1",
    title: "Budapest",
    artist: "George Ezra",
    album: "Wanted on Voyage",
    duration: "3:21",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2ixsaeFioXJmMgkkbd4uj1",
    moods: ["joyeux", "chill"],
    energy: 50,
    note: "Pour prendre l'air (lol)",
  },
  {
    id: "66tkDkPsznE5zIHNt4QkXB",
    title: "Tieduprightnow",
    artist: "Parcels",
    album: "Tieduprightnow",
    duration: "3:34",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/66tkDkPsznE5zIHNt4QkXB",
    moods: ["joyeux", "chill"],
    energy: 60,
    note: "Pour une ambiance solaire",
  },
  {
    id: "44BdgwXryaVltM1ixhWZoA",
    title: "J'irai où tu iras",
    artist: "Céline Dion & Jean-Jacques Goldman",
    album: "D'Eux",
    duration: "4:03",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/44BdgwXryaVltM1ixhWZoA",
    moods: ["joyeux", "romantique", "energique"],
    energy: 75,
    note: "Pour crier (chanter) à plein poumons",
  },

  // 💕 Romantique
  {
    id: "4YbIFEc9dCJLC3fpaSXnDN",
    title: "Mais je t'aime",
    artist: "Grand Corps Malade & Camille Lellouche",
    album: "Mesdames",
    duration: "4:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4YbIFEc9dCJLC3fpaSXnDN",
    moods: ["romantique", "melancolique"],
    energy: 50,
    note: "Pour des mots justes",
  },
  {
    id: "7i6VLLVRwLSXgqWlvjyyOy",
    title: "Comme toi",
    artist: "Jean-Jacques Goldman",
    album: "Quand la musique est bonne",
    duration: "3:48",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7i6VLLVRwLSXgqWlvjyyOy",
    moods: ["romantique", "melancolique"],
    energy: 35,
    note: "Pour penser à ceux qu'on aime vraiment",
  },
  {
    id: "1tmvcgRZR7yLqtbMLqmZ2I",
    title: "Je te promets",
    artist: "Johnny Hallyday",
    album: "Gang",
    duration: "5:27",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1tmvcgRZR7yLqtbMLqmZ2I",
    moods: ["romantique", "melancolique"],
    energy: 55,
    note: "Pour les promesses qu'on croit encore",
  },
  {
    id: "44AyOl4qVkzS48vBsbNXaC",
    title: "Can't Help Falling in Love",
    artist: "Elvis Presley",
    album: "Blue Hawaii",
    duration: "3:00",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/44AyOl4qVkzS48vBsbNXaC",
    moods: ["romantique", "chill"],
    energy: 25,
    note: "Pour un moment d'amour fou",
  },
  {
    id: "2IuSwhpsmWdDsMUvWIzX6x",
    title: "Je l'attendais",
    artist: "Michel Delpech",
    album: "CD Story",
    duration: "3:24",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2IuSwhpsmWdDsMUvWIzX6x",
    moods: ["romantique", "joyeux"],
    energy: 45,
    note: "Pour croire aux évidences",
  },
  {
    id: "0kVE2yBjTwnFqbsrXRKg5Y",
    title: "I Just Called to Say I Love You",
    artist: "Stevie Wonder",
    album: "The Woman in Red",
    duration: "4:20",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0kVE2yBjTwnFqbsrXRKg5Y",
    moods: ["romantique", "joyeux"],
    energy: 45,
    note: "Pour se regarder avec les yeux doux",
  },
  {
    id: "2Desf0YgquK9YrSkRhkvDN",
    title: "Les Mots Bleus",
    artist: "Christophe",
    album: "Les mots bleus",
    duration: "4:21",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2Desf0YgquK9YrSkRhkvDN",
    moods: ["romantique", "melancolique"],
    energy: 30,
    note: "Pour une poésie",
  },
  {
    id: "5dXJ1SoksFkgdx3yxIoYNO",
    title: "You're The First, The Last, My Everything",
    artist: "Barry White",
    album: "Can't Get Enough",
    duration: "4:33",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/5dXJ1SoksFkgdx3yxIoYNO",
    moods: ["romantique", "joyeux", "energique"],
    energy: 65,
    note: "Pour se rappeler qu'on est iconic",
  },
  {
    id: "6jG2YzhxptolDzLHTGLt7S",
    title: "Drunk in Love",
    artist: "Beyoncé ft. JAY-Z",
    album: "BEYONCÉ [Platinum Edition]",
    duration: "5:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6jG2YzhxptolDzLHTGLt7S",
    moods: ["romantique", "energique", "fetard"],
    energy: 70,
    note: "Pour se rappeler qu'on est puissant.e",
  },

  // 😌 Chill
  {
    id: "1xWH7lhR9YSWRyhKgvARfv",
    title: "Sunset Lover",
    artist: "Petit Biscuit",
    album: "Petit Biscuit",
    duration: "3:48",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1xWH7lhR9YSWRyhKgvARfv",
    moods: ["chill"],
    energy: 35,
    note: "Pour une soirée douce",
  },
  {
    id: "2W3EgJst61RLZtPPm3EQim",
    title: "Territory",
    artist: "The Blaze",
    album: "Territory",
    duration: "3:49",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/2W3EgJst61RLZtPPm3EQim",
    moods: ["chill"],
    energy: 45,
    note: "Pour lâcher prise",
  },
  {
    id: "6CGMZijOAZvTXG21T8t6R0",
    title: "Innerbloom",
    artist: "RÜFÜS DU SOL",
    album: "Bloom",
    duration: "9:35",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6CGMZijOAZvTXG21T8t6R0",
    moods: ["chill"],
    energy: 40,
    note: "Pour viber ensemble",
  },
  {
    id: "4pO7pWnbbULCZgENjDksTQ",
    title: "Sisteron",
    artist: "Kiasmos",
    album: "Sisteron",
    duration: "5:30",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4pO7pWnbbULCZgENjDksTQ",
    moods: ["chill", "melancolique"],
    energy: 35,
    note: "Dédicace au 07/07/26",
  },
  {
    id: "3ZSqMer9RLSglvi18bWXYV",
    title: "Sky and Sand",
    artist: "Paul Kalkbrenner & Fritz Kalkbrenner",
    album: "Berlin Calling",
    duration: "7:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3ZSqMer9RLSglvi18bWXYV",
    moods: ["chill"],
    energy: 50,
    note: "Pour du pur kiff",
  },
  {
    id: "4FOFC3YNvDgLesoVqRthZh",
    title: "Spanish Grease",
    artist: "Willie Bobo",
    album: "Spanish Grease",
    duration: "2:46",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4FOFC3YNvDgLesoVqRthZh",
    moods: ["chill", "joyeux"],
    energy: 50,
    note: "Pour voyager en un clic",
  },
  {
    id: "0zO8ctW0UiuOefR87OeJOZ",
    title: "Collard Greens",
    artist: "ScHoolboy Q ft. Kendrick Lamar",
    album: "Oxymoron",
    duration: "3:57",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0zO8ctW0UiuOefR87OeJOZ",
    moods: ["chill"],
    energy: 55,
    note: "Pour une vibe cool",
  },
  {
    id: "1JSTJqkT5qHq8MDJnJbRE1",
    title: "Every Breath You Take",
    artist: "The Police",
    album: "Synchronicity",
    duration: "4:13",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1JSTJqkT5qHq8MDJnJbRE1",
    moods: ["chill", "romantique"],
    energy: 35,
    note: "Pour une ambiance calme",
  },

  // 🥺 Mélancolique
  {
    id: "1raWfcURBd1Q3W3K0ojDCM",
    title: "Now We Are Free",
    artist: "Hans Zimmer & Lisa Gerrard",
    album: "Gladiator (Soundtrack)",
    duration: "4:15",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/1raWfcURBd1Q3W3K0ojDCM",
    moods: ["melancolique"],
    energy: 30,
    note: "Pour se sentir invincibles",
  },
  {
    id: "3D2wU177Hr5AXTePqaC8KQ",
    title: "Générique de fin",
    artist: "Youssef Swatt's",
    album: "Nouvelle École Saison 3",
    duration: "3:45",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3D2wU177Hr5AXTePqaC8KQ",
    moods: ["melancolique"],
    energy: 45,
    note: "Rpz Tournai 🇧🇪",
  },

  // ⚡ Énergique
  {
    id: "4vS8VaBwJJV5Ry7UFIQuoo",
    title: "Lean On",
    artist: "Major Lazer & DJ Snake ft. MØ",
    album: "Peace Is The Mission",
    duration: "2:56",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/4vS8VaBwJJV5Ry7UFIQuoo",
    moods: ["energique", "fetard"],
    energy: 80,
    note: "Pour un comeback en rhéto",
  },
  {
    id: "314QzMOrpNUqWBUozYshf6",
    title: "Buttons",
    artist: "The Pussycat Dolls",
    album: "PCD",
    duration: "3:46",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/314QzMOrpNUqWBUozYshf6",
    moods: ["energique", "fetard"],
    energy: 75,
    note: "Pour se sentir sexy mamacita",
  },
  {
    id: "0N3W5peJUQtI4eyR6GJT5O",
    title: "King Kunta",
    artist: "Kendrick Lamar",
    album: "To Pimp A Butterfly",
    duration: "3:54",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0N3W5peJUQtI4eyR6GJT5O",
    moods: ["energique", "fetard"],
    energy: 80,
    note: "Pour se sentir comme un boss",
  },

  // 🎉 Fêtard
  {
    id: "303ccTay2FiDTZ9fZ2AdBt",
    title: "Music Sounds Better with You",
    artist: "Stardust",
    album: "Music Sounds Better with You",
    duration: "5:07",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/303ccTay2FiDTZ9fZ2AdBt",
    moods: ["fetard"],
    energy: 80,
    note: "Pour se croire sur le dancefloor",
  },
  {
    id: "5c64Kh5iR9SbMNJADYenFf",
    title: "Free from Desire",
    artist: "Gala",
    album: "Come Into My Life",
    duration: "4:00",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/5c64Kh5iR9SbMNJADYenFf",
    moods: ["fetard"],
    energy: 85,
    note: "Pour une soirée nostalgie assumée",
  },
  {
    id: "3djNBlI7xOggg7pnsOLaNm",
    title: "California Love",
    artist: "2Pac ft. Dr. Dre & Roger",
    album: "The Best of 2Pac",
    duration: "4:45",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3djNBlI7xOggg7pnsOLaNm",
    moods: ["fetard", "energique"],
    energy: 80,
    note: "Pour une vibe 90's",
  },
  {
    id: "6IJmRILFspEP80BmmfAv2m",
    title: "Femme Like U",
    artist: "K.Maro",
    album: "La Good Life",
    duration: "3:23",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/6IJmRILFspEP80BmmfAv2m",
    moods: ["fetard"],
    energy: 75,
    note: "Pour le plaisir coupable",
  },
  {
    id: "76TBja3GNcBipLdbXJdvTG",
    title: "Murder on the Dancefloor",
    artist: "Sophie Ellis-Bextor",
    album: "Read My Lips",
    duration: "3:51",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/76TBja3GNcBipLdbXJdvTG",
    moods: ["fetard"],
    energy: 80,
    note: "Pour danser sans retenue",
  },
  {
    id: "7iL6o9tox1zgHpKUfh9vuC",
    title: "In Da Club",
    artist: "50 Cent",
    album: "Get Rich or Die Tryin'",
    duration: "3:13",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/7iL6o9tox1zgHpKUfh9vuC",
    moods: ["fetard", "energique"],
    energy: 85,
    note: "Pour faire ressortir Valouze x Firechang",
  },
  {
    id: "0kKevClVVLtgRm3oyYJnq8",
    title: "Destination Calabria",
    artist: "Alex Gaudino ft. Crystal Waters",
    album: "My Destination",
    duration: "3:06",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/0kKevClVVLtgRm3oyYJnq8",
    moods: ["fetard"],
    energy: 90,
    note: "Putain de fiesta, on est chaud !!",
  },
  {
    id: "3SQY5MzR2wJAUjqGEIJk69",
    title: "Living on Video",
    artist: "Pakito",
    album: "Living on Video",
    duration: "3:14",
    coverUrl: "",
    spotifyUrl: "https://open.spotify.com/track/3SQY5MzR2wJAUjqGEIJk69",
    moods: ["fetard"],
    energy: 90,
    note: "Pour une nostalgie bien kitsch qu'on adore",
  },
];
